import { ProjectStatus } from "./interfaces";
export const projectStatus = {
    Pending: [
      // 'Design of Solar-Powered Street Lighting System',
      // 'Development of Autonomous Agricultural Drone',
      // 'Wireless Power Transfer for Electric Vehicles',
    ],
    Accepted: [
      // 'Design and Fabrication of Automated Greenhouse System',
      // 'Smart Grid Implementation for Rural Areas',
      // 'AI-based Predictive Maintenance for Industrial Equipment',
      {
      name: 'Design and Fabrication of Automated Greenhouse System',
      category: 'Engineering',
      id: 'A001',
      grant: 'Grant D',
      duration: '12 months',
      budget: 120000,
      description: 'Project to design and fabricate an automated greenhouse system.',
      equipments: [
        {
          name: 'Greenhouse Climate Control System',
          specs: 'Temperature and humidity control, Wi-Fi enabled',
          quantity: 1,
          justification: 'To maintain optimal climate conditions inside the greenhouse.',
          file: { documentName: 'climate_control_spec.pdf', documentURL: 'http://example.com/climate_control_spec.pdf' }
        },
        {
          name: 'Automated Irrigation System',
          specs: 'Soil moisture sensors, drip irrigation',
          quantity: 1,
          justification: 'To provide efficient watering to plants based on soil moisture levels.',
          file: { documentName: 'irrigation_spec.pdf', documentURL: 'http://example.com/irrigation_spec.pdf' }
        }
      ],
      document: [],
      status: ProjectStatus.APPROVED,
      date: '11/01/2023', // MM/DD/YYYY format
    },
    {
      name: 'Smart Grid Implementation for Rural Areas',
      category: 'Technology',
      id: 'A002',
      grant: 'Grant E',
      duration: '15 months',
      budget: 180000,
      description: 'Implementing smart grids in rural areas for efficient energy use.',
      equipments: [
        {
          name: 'Smart Meters',
          specs: 'Digital, two-way communication, remote monitoring',
          quantity: 50,
          justification: 'To monitor energy usage and improve grid efficiency.',
          file: { documentName: 'smart_meter_spec.pdf', documentURL: 'http://example.com/smart_meter_spec.pdf' }
        },
        {
          name: 'Energy Storage Systems',
          specs: 'Lithium-ion, 5kWh',
          quantity: 10,
          justification: 'To store excess energy generated by renewable sources.',
          file: { documentName: 'storage_system_spec.pdf', documentURL: 'http://example.com/storage_system_spec.pdf' }
        }
      ],
      document: [],
      status: ProjectStatus.APPROVED,
      date: '10/15/2023', // MM/DD/YYYY format
    },
    {
      name: 'AI-based Predictive Maintenance for Industrial Equipment',
      category: 'Technology',
      id: 'A003',
      grant: 'Grant F',
      duration: '10 months',
      budget: 150000,
      description: 'Developing AI-based predictive maintenance for industrial machinery.',
      equipments: [
        {
          name: 'Vibration Sensors',
          specs: 'For monitoring machine vibrations, wireless',
          quantity: 15,
          justification: 'For detecting abnormal vibrations that indicate potential failures.',
          file: { documentName: 'vibration_sensor_spec.pdf', documentURL: 'http://example.com/vibration_sensor_spec.pdf' }
        },
        {
          name: 'Data Analysis Software',
          specs: 'AI-based software for predictive analysis',
          quantity: 5,
          justification: 'For analyzing sensor data and predicting maintenance needs.',
          file: { documentName: 'software_spec.pdf', documentURL: 'http://example.com/software_spec.pdf' }
        }
      ],
      document: [],
      status: ProjectStatus.APPROVED,
      date: '09/01/2023', // MM/DD/YYYY format
    }
    ],
    Rejected: [
      // '3D Printing of Customized Prosthetics',
      // 'Design of Hybrid Electric Vehicle for Urban Transportation',
      // 'Development of Smart Wearable Health Monitoring System',
      {
        name: '3D Printing of Customized Prosthetics',
        category: 'Healthcare',
        id: 'R001',
        grant: 'Grant G',
        duration: '8 months',
        budget: 100000,
        description: 'Project to use 3D printing for creating customized prosthetics.',
        equipments: [
          {
            name: '3D Printer',
            specs: 'FDM, 0.1mm precision, dual extrusion',
            quantity: 2,
            justification: 'To print the prosthetics.',
            file: { documentName: '3d_printer_spec.pdf', documentURL: 'http://example.com/3d_printer_spec.pdf' }
          },
          {
            name: 'Medical-Grade Filament',
            specs: 'PLA, biocompatible, 1.75mm',
            quantity: 10,
            justification: 'To create durable and safe prosthetics.',
            file: { documentName: 'filament_spec.pdf', documentURL: 'http://example.com/filament_spec.pdf' }
          }
        ],
        document: [],
        status: ProjectStatus.REJECTED,
        date: '08/01/2023', // MM/DD/YYYY format
      },
      {
        name: 'Design of Hybrid Electric Vehicle for Urban Transportation',
        category: 'Engineering',
        id: 'R002',
        grant: 'Grant H',
        duration: '24 months',
        budget: 250000,
        description: 'Design and prototype of a hybrid electric vehicle for urban use.',
        equipments: [
          {
            name: 'Electric Motors',
            specs: 'Brushless DC motors, 150kW',
            quantity: 4,
            justification: 'For propulsion of the hybrid vehicle.',
            file: { documentName: 'motor_spec.pdf', documentURL: 'http://example.com/motor_spec.pdf' }
          },
          {
            name: 'Battery Pack',
            specs: 'Lithium-ion, 200V, 50Ah',
            quantity: 2,
            justification: 'To power the electric motor.',
            file: { documentName: 'battery_pack_spec.pdf', documentURL: 'http://example.com/battery_pack_spec.pdf' }
          }
        ],
        document: [],
        status: ProjectStatus.REJECTED,
        date: '07/01/2023', // MM/DD/YYYY format
      },
      {
        name: 'Development of Smart Wearable Health Monitoring System',
        category: 'Healthcare',
        id: 'R003',
        grant: 'Grant I',
        duration: '16 months',
        budget: 200000,
        description: 'Developing a smart wearable system for monitoring health metrics.',
        equipments: [
          {
            name: 'Wearable Sensors',
            specs: 'Heart rate, blood pressure, and temperature monitoring',
            quantity: 100,
            justification: 'For monitoring the user’s health metrics.',
            file: { documentName: 'sensor_spec.pdf', documentURL: 'http://example.com/sensor_spec.pdf' }
          },
          {
            name: 'Mobile App Development Tools',
            specs: 'Cross-platform development tools for iOS and Android',
            quantity: 2,
            justification: 'To develop the app for data visualization.',
            file: { documentName: 'app_dev_spec.pdf', documentURL: 'http://example.com/app_dev_spec.pdf' }
          }
        ],
        document: [],
        status: ProjectStatus.REJECTED,
        date: '06/01/2023', // MM/DD/YYYY format
      }
    
    ],
  };